In [48]:
import pandas as pd

In [49]:
dataset_market_1 = [['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
           ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
           ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

In [50]:
from mlxtend.preprocessing import TransactionEncoder
encoder = TransactionEncoder()
data = encoder.fit(dataset_market_1).transform(dataset_market_1).astype('int')

In [51]:
data

array([[0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1],
       [0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1],
       [0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0]])

In [52]:
data = pd.DataFrame(data)

In [53]:
data

   0   1   2   3   4   5   6   7   8   9   10
0   0   0   0   1   0   1   1   1   1   0   1
1   0   0   1   1   0   1   0   1   1   0   1
2   1   0   0   1   0   1   1   0   0   0   0
3   0   1   0   0   0   1   1   0   0   1   1
4   0   1   0   1   1   1   0   0   1   0   0

In [54]:
data.columns=encoder.columns_

In [55]:
data

,Apple,Corn,Dill,Eggs,Ice cream,Kidney Beans,Milk,Nutmeg,Onion,Unicorn,Yogurt
0,0,0,0,1,0,1,1,1,1,0,1
1,0,0,1,1,0,1,0,1,1,0,1
2,1,0,0,1,0,1,1,0,0,0,0
3,0,1,0,0,0,1,1,0,0,1,1
4,0,1,0,1,1,1,0,0,1,0,0

In [56]:
from mlxtend.frequent_patterns import apriori

In [59]:
data_assoc = apriori(data , min_support = 0.5 , use_colnames=True )

C:\Users\User\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [60]:
data_assco

    support   itemsets
0       0.8        (3)
1       1.0        (5)
2       0.6        (6)
3       0.6        (8)
4       0.6       (10)
5       0.8     (3, 5)
6       0.6     (8, 3)
7       0.6     (5, 6)
8       0.6     (8, 5)
9       0.6    (10, 5)
10      0.6  (8, 3, 5)

In [45]:
from mlxtend.frequent_patterns import association_rules

In [46]:
rules = association_rules(data_assoc , metric = 'confidence', min_threshold = 0.6)

C:\Users\User\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\association_rules.py:186: RuntimeWarning: invalid value encountered in divide
  cert_metric = np.where(certainty_denom == 0, 0, certainty_num / certainty_denom)

In [47]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Eggs),(Kidney Beans),0.8,1.0,0.8,1.00,1.00,1.0,0.00,inf,0.0,0.80,0.000,0.900
1,(Kidney Beans),(Eggs),1.0,0.8,0.8,0.80,1.00,1.0,0.00,1.0,0.0,0.80,0.000,0.900
2,(Eggs),(Onion),0.8,0.6,0.6,0.75,1.25,1.0,0.12,1.6,1.0,0.75,0.375,0.875
3,(Onion),(Eggs),0.6,0.8,0.6,1.00,1.25,1.0,0.12,inf,0.5,0.75,1.000,0.875
4,(Kidney Beans),(Milk),1.0,0.6,0.6,0.60,1.00,1.0,0.00,1.0,0.0,0.60,0.000,0.800
5,(Milk),(Kidney Beans),0.6,1.0,0.6,1.00,1.00,1.0,0.00,inf,0.0,0.60,0.000,0.800
6,(Kidney Beans),(Onion),1.0,0.6,0.6,0.60,1.00,1.0,0.00,1.0,0.0,0.60,0.000,0.800
7,(Onion),(Kidney Beans),0.6,1.0,0.6,1.00,1.00,1.0,0.00,inf,0.0,0.60,0.000,0.800
8,(Kidney Beans),(Yogurt),1.0,0.6,0.6,0.60,1.00,1.0,0.00,1.0,0.0,0.60,0.000,0.800
9,(Yogurt),(Kidney Beans),0.6,1.0,0.6,1.00,1.00,1.0,0.00,inf,0.0,0.60,0.000,0.800
10,"(Eggs, Kidney Beans)",(Onion),0.8,0.6,0.6,0.75,1.25,1.0,0.12,1.6,1.0,0.75,0.375,0.875
11,"(Eggs, Onion)",(Kidney Beans),0.6,1.0,0.6,1.00,1.00,1.0,0.00,inf,0.0,0.60,0.000,0.800
12,"(Kidney Beans, Onion)",(Eggs),0.6,0.8,0.6,1.00,1.25,1.0,0.12,inf,0.5,0.75,1.000,0.875
13,(Eggs),"(Kidney Beans, Onion)",0.8,0.6,0.6,0.75,1.25,1.0,0.12,1.6,1.0,0.75,0.375,0.875
14,(Kidney Beans),"(Eggs, Onion)",1.0,0.6,0.6,0.60,1.00,1.0,0.00,1.0,0.0,0.60,0.000,0.800
15,(Onion),"(Eggs, Kidney Beans)",0.6,0.8,0.6,1.00,1.25,1.0,0.12,inf,0.5,0.75,1.000,0.875

In [1]:
import pandas as pd

In [2]:
dataset_market_1 = [['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
           ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
           ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

In [31]:
from mlxtend.preprocessing import TransactionEncoder
tran = TransactionEncoder()
array = tran.fit(dataset_market_1).transform(dataset_market_1).astype('int')

In [32]:
array

array([[0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1],
       [0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1],
       [0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0]])

In [33]:
data = pd.DataFrame(array)

In [34]:
data

   0   1   2   3   4   5   6   7   8   9   10
0   0   0   0   1   0   1   1   1   1   0   1
1   0   0   1   1   0   1   0   1   1   0   1
2   1   0   0   1   0   1   1   0   0   0   0
3   0   1   0   0   0   1   1   0   0   1   1
4   0   1   0   1   1   1   0   0   1   0   0

In [35]:
data.columns=tran.columns_

In [36]:
from mlxtend.frequent_patterns import apriori , association_rules

In [37]:
freq_data = apriori(data , min_support = 0.3 , use_colnames =True)

C:\Users\User\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [38]:
freq_data

    support                                     itemsets
0       0.4                                       (Corn)
1       0.8                                       (Eggs)
2       1.0                               (Kidney Beans)
3       0.6                                       (Milk)
4       0.4                                     (Nutmeg)
5       0.6                                      (Onion)
6       0.6                                     (Yogurt)
7       0.4                         (Corn, Kidney Beans)
8       0.8                         (Eggs, Kidney Beans)
9       0.4                                 (Eggs, Milk)
10      0.4                               (Eggs, Nutmeg)
11      0.6                                (Eggs, Onion)
12      0.4                               (Eggs, Yogurt)
13      0.6                         (Milk, Kidney Beans)
14      0.4                       (Nutmeg, Kidney Beans)
15      0.6                        (Onion, Kidney Beans)
16      0.6                       (Yogurt, Kidney Beans)
17      0.4                               (Milk, Yogurt)
18      0.4                              (Onion, Nutmeg)
19      0.4                             (Nutmeg, Yogurt)
20      0.4                              (Onion, Yogurt)
21      0.4                   (Eggs, Milk, Kidney Beans)
22      0.4                 (Eggs, Nutmeg, Kidney Beans)
23      0.6                  (Eggs, Onion, Kidney Beans)
24      0.4                 (Eggs, Yogurt, Kidney Beans)
25      0.4                        (Eggs, Onion, Nutmeg)
26      0.4                       (Eggs, Nutmeg, Yogurt)
27      0.4                        (Eggs, Onion, Yogurt)
28      0.4                 (Milk, Yogurt, Kidney Beans)
29      0.4                (Onion, Nutmeg, Kidney Beans)
30      0.4               (Nutmeg, Yogurt, Kidney Beans)
31      0.4                (Onion, Yogurt, Kidney Beans)
32      0.4                      (Onion, Nutmeg, Yogurt)
33      0.4          (Eggs, Onion, Nutmeg, Kidney Beans)
34      0.4         (Eggs, Nutmeg, Yogurt, Kidney Beans)
35      0.4          (Eggs, Onion, Yogurt, Kidney Beans)
36      0.4                (Eggs, Onion, Nutmeg, Yogurt)
37      0.4        (Onion, Nutmeg, Yogurt, Kidney Beans)
38      0.4  (Yogurt, Kidney Beans, Nutmeg, Eggs, Onion)

In [39]:
ass_data = association_rules(freq_data , metric = 'confidence' , min_threshold=0.6)

C:\Users\User\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\association_rules.py:186: RuntimeWarning: invalid value encountered in divide
  cert_metric = np.where(certainty_denom == 0, 0, certainty_num / certainty_denom)

In [40]:
ass_data

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Corn),(Kidney Beans),0.4,1.0,0.4,1.000000,1.000000,1.0,0.00,inf,0.000000,0.400000,0.000000,0.700000
1,(Eggs),(Kidney Beans),0.8,1.0,0.8,1.000000,1.000000,1.0,0.00,inf,0.000000,0.800000,0.000000,0.900000
2,(Kidney Beans),(Eggs),1.0,0.8,0.8,0.800000,1.000000,1.0,0.00,1.0,0.000000,0.800000,0.000000,0.900000
3,(Milk),(Eggs),0.6,0.8,0.4,0.666667,0.833333,1.0,-0.08,0.6,-0.333333,0.400000,-0.666667,0.583333
4,(Nutmeg),(Eggs),0.4,0.8,0.4,1.000000,1.250000,1.0,0.08,inf,0.333333,0.500000,1.000000,0.750000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,"(Onion, Nutmeg)","(Eggs, Yogurt, Kidney Beans)",0.4,0.4,0.4,1.000000,2.500000,1.0,0.24,inf,1.000000,1.000000,1.000000,1.000000
161,"(Eggs, Onion)","(Nutmeg, Yogurt, Kidney Beans)",0.6,0.4,0.4,0.666667,1.666667,1.0,0.16,1.8,1.000000,0.666667,0.444444,0.833333
162,(Yogurt),"(Eggs, Onion, Nutmeg, Kidney Beans)",0.6,0.4,0.4,0.666667,1.666667,1.0,0.16,1.8,1.000000,0.666667,0.444444,0.833333
163,(Nutmeg),"(Eggs, Onion, Yogurt, Kidney Beans)",0.4,0.4,0.4,1.000000,2.500000,1.0,0.24,inf,1.000000,1.000000,1.000000,1.000000
164,(Onion),"(Eggs, Nutmeg, Yogurt, Kidney Beans)",0.6,0.4,0.4,0.666667,1.666667,1.0,0.16,1.8,1.000000,0.666667,0.444444,0.833333